
class K:

    Z = 2.576  # confidence interval Z=2 --> 95.45% ; Z=3 --> 99.7% ; Z=4 --> 99.99% ; Z = 2.576 --> 99%
    MSG_REAL = 0
    MSG_MEASUREMENT = 1
    MSG_DUMMY = 2
    # corrupt mix (1) or honest (0)
    MIX_HONEST = 0
    MIX_CORRUPT = 1
    MIX_TARGET = 2
    NOBODY = -1
    GW_BROADCAST = 0
    CLIENT = -99
    # type of mix
    MIX = 10
    GATEWAY = 11
    PLACEHOLDER_CLIENTS = -99
    # direction messages wrt node
    INBOUND = 0
    OUTBOUND = 1
    TICKS_PER_SECOND = 0.1  # factor 10: sim_duration = 1.0 --> 10s of sim
    TPS = TICKS_PER_SECOND
    TRANSMISSION_TIME = 0.040 * TPS  # we consider 40ms of transmission delay
    PROCESSING_TIME_GATEWAYS = 0.002 * TPS  # we consider 2ms of processing delay at gateways
    GRACE_PERIOD_END_SIM = 3.0 * TPS  # 3 seconds grace period to allow messages finish routing
    # traffic volume generated by clients
    VOLUME_BASELINE = 1
    VOLUME_HIGH = 2
    # message creation/destruction action codes
    CREATE = 100
    RECEIVE = 101
    DROP = 102

    MIN_SAMPLES = 25  # minimum nr of samples to consider the performance of a link in the layer set of links
    MAX_DIFF_P66_ESTIMATE = 0.001  # of difference between p66 and estimated value is higher than 0.1% then mark as anomaly
